using Content.Shared.Botany.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Botany.PlantAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerControl : BoxContainer
{
    private readonly SpriteSystem _spriteSystem;
    private static readonly Color BarGreen = new(0.20f, 0.80f, 0.25f);
    private static readonly Color BarYellow = new(1.00f, 0.78f, 0.18f);
    private static readonly Color BarRed = new(0.90f, 0.12f, 0.12f);
    public PlantAnalyzerControl()
    {
        RobustXamlLoader.Load(this);
        _spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
    }

    public void Populate(PlantAnalyzerUiState state)
    {
        NoPlantDataText.Visible = !state.HasPlant;
        PlantDataContainer.Visible = state.HasPlant;

        if (!state.HasPlant)
        {
            NoPlantDataText.Text = Loc.GetString("plant-analyzer-interface-no-plant");
            return;
        }

        ScanModeLabel.Text = state.ScanMode
            ? Loc.GetString("plant-analyzer-interface-status-active")
            : Loc.GetString("plant-analyzer-interface-status-inactive");

        var plantName = new FormattedMessage();
        plantName.AddText(string.IsNullOrWhiteSpace(state.PlantName)
            ? Loc.GetString("plant-analyzer-value-unknown")
            : state.PlantName);

        PlantNameLabel.SetMessage(plantName);

        HealthLabel.Text = $"{state.Health:F1}";
        AgeLabel.Text = $"{state.Age}";
        DeadLabel.Text = YesNo(state.Dead);
        HarvestLabel.Text = YesNo(state.Harvest);

        WaterLabel.Text = $"{state.WaterLevel:F1}";
        NutritionLabel.Text = $"{state.NutritionLevel:F1}";
        WeedsLabel.Text = $"{state.WeedLevel:F1}";
        PestsLabel.Text = $"{state.PestLevel:F1}";
        ToxinsLabel.Text = $"{state.Toxins:F1}";

        YieldLabel.Text = $"{state.Yield}";
        PotencyLabel.Text = $"{state.Potency:F1}";
        EnduranceLabel.Text = $"{state.Endurance:F1}";
        LifespanLabel.Text = $"{state.Lifespan:F1}";
        MaturationLabel.Text = $"{state.Maturation:F1}";
        ProductionLabel.Text = $"{state.Production:F1}";

        IdealHeatLabel.Text = $"{state.IdealHeat:F1}";
        HeatToleranceLabel.Text = $"{state.HeatTolerance:F1}";
        IdealLightLabel.Text = $"{state.IdealLight:F1}";
        LightToleranceLabel.Text = $"{state.LightTolerance:F1}";

        PopulateWarnings(state);
        PopulateTraits(state);
        PopulateChemicals(state);
        PopulateOverviewBars(state);
        PopulatePlantSprite(state);
    }

    private void PopulatePlantSprite(PlantAnalyzerUiState state)
    {
        PlantSprite.Texture = null;
        GrowthStageLabel.Text = string.Empty;

        if (string.IsNullOrWhiteSpace(state.PlantSpriteRsi) ||
            string.IsNullOrWhiteSpace(state.PlantSpriteState))
        {
            PlantSprite.Visible = false;
            return;
        }

        PlantSprite.Visible = true;

        var sprite = new SpriteSpecifier.Rsi(
            new ResPath(state.PlantSpriteRsi),
            state.PlantSpriteState);

        PlantSprite.Texture = _spriteSystem.Frame0(sprite);

        if (state.GrowthStage > 0)
            GrowthStageLabel.Text = $"Growth stage: {state.GrowthStage}";
    }
    private void PopulateOverviewBars(PlantAnalyzerUiState state)
    {
        PopulateAgeBar(state);
        PopulateHealthBar(state);
    }

    private void PopulateAgeBar(PlantAnalyzerUiState state)
    {
        var age = MathF.Max(0f, state.Age);
        var maturation = MathF.Max(1f, state.Maturation);
        var lifespan = MathF.Max(maturation, state.Lifespan);

        Color color;
        string status;
        string tooltip;
        float capacity = MathF.Max(lifespan, age + 10f);

        if (age > lifespan)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-age-old");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-old",
                ("lifespan", $"{lifespan:0.#}"));
        }
        else if (age >= maturation)
        {
            color = BarGreen;
            status = Loc.GetString("plant-analyzer-age-mature");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-mature",
                ("lifespan", $"{lifespan:0.#}"));
        }
        else
        {
            color = BarYellow;
            status = Loc.GetString("plant-analyzer-age-growing");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-growing",
                ("maturation", $"{maturation:0.#}"));
        }

        if (state.Dead)
        {
            color = BarRed;
            capacity = lifespan;
        }

        AgeStatusLabel.Text = status;

        float nextHarvestAge = GetNextHarvestAge(state) ?? capacity;
        var markerTooltip = Loc.GetString(
                state.Harvest
                    ? "plant-analyzer-age-tooltip-harvest-ready"
                    : "plant-analyzer-age-tooltip-next-harvest",
                ("age", $"{nextHarvestAge:0.#}"));

        AgeBar.SetData(
            age,
            capacity,
            color,
            Loc.GetString(
                "plant-analyzer-age-bar-text",
                ("age", $"{age:0.#}"),
                ("limit", $"{lifespan:0.#}")),
            tooltip);
        AgeBar.AddNotch(width: 1f, height: 0.2f, bottomAlign: true);
        AgeBar.AddNotch(width: 5f, height: 0.4f, bottomAlign: true);
        //Don't show next harvest if it's dead
        if (!state.Dead)
        {
            AgeBar.AddNotch(
                width: MathF.Floor(state.Production) + 1f,
                height: 0.3f,
                offset: nextHarvestAge,
                bottomAlign: false,
                //If it's multiharvest, show all potential harvests.  Otherwise only show one.
                count: state.MultiHarvest ? 0 : 1,
                //Violet if self-harvesting, sky blue if regular harvest
                notchColor: state.AutoHarvest ? new Color(0.6f, 0.2f, 0.9f, 0.25f) : new Color(0.4f, 0.8f, 1f, 0.25f),
                tooltipText: markerTooltip);
        }
    }

    private void PopulateHealthBar(PlantAnalyzerUiState state)
    {
        var maxHealth = MathF.Max(1f, state.Endurance);
        var health = MathHelper.Clamp(state.Health, 0f, maxHealth);
        var unhealthyThreshold = maxHealth / 2f;

        var isUnhealthy = health <= unhealthyThreshold;

        var isStressed =
            !state.Viable ||
            state.Age > state.Lifespan ||
            state.ImproperHeat ||
            state.ImproperPressure ||
            state.ImproperLight ||
            state.MissingGas > 0 ||
            state.WeedLevel > state.WeedTolerance ||
            state.Toxins > state.ToxinsTolerance ||
            state.PestLevel > state.PestTolerance;

        Color color;
        string status;
        string tooltip;
        string healthText = Loc.GetString("plant-analyzer-health-bar-text",
                                            ("health", $"{health:0.#}"),
                                            ("maxHealth", $"{maxHealth:0.#}"));

        if (state.Dead)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-health-dead");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-dead");
            healthText = Loc.GetString("plant-analyzer-health-dead");
        }
        else if (isStressed)
        {
            color = isUnhealthy ? BarRed : BarYellow;
            status = Loc.GetString("plant-analyzer-health-stressed");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-stressed");
        }
        else if (isUnhealthy)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-health-stressed");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-unhealthy");
        }
        else
        {
            color = BarGreen;
            status = Loc.GetString("plant-analyzer-health-healthy");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-healthy");
        }

        HealthStatusLabel.Text = status;


        HealthBar.SetData(
            health,
            maxHealth,
            color,
            healthText,
            tooltip);
        if (!state.Dead)
        {
            HealthBar.AddNotch(width: 5f, height: 0.2f, bottomAlign: true);
            HealthBar.AddNotch(width: 10f, height: 0.4f, bottomAlign: true);
        }

        PopulateHealthIssues(state, health, unhealthyThreshold);
    }

    private void PopulateHealthIssues(
    PlantAnalyzerUiState state,
    float health,
    float unhealthyThreshold)
    {
        HealthIssuesContainer.RemoveAllChildren();

        var foundIssue = false;

        if (state.Dead)
        {
            AddHealthIssue("plant-analyzer-health-issue-dead");
            foundIssue = true;
            return;
        }

        if (state.Age > state.Lifespan)
        {
            AddHealthIssue("plant-analyzer-health-issue-old");
            foundIssue = true;
        }

        if (!state.Viable)
        {
            AddHealthIssue("plant-analyzer-health-issue-nonviable");
            foundIssue = true;
        }

        if (state.NutritionLevel <= 5)
        {
            AddHealthIssue("plant-analyzer-health-issue-nutrients");
            foundIssue = true;
        }


        if (state.WaterLevel <= 10)
        {
            AddHealthIssue("plant-analyzer-health-issue-water");
            foundIssue = true;
        }


        if (state.ImproperHeat)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-heat");
            foundIssue = true;
        }


        if (state.ImproperHeat)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-heat");
            foundIssue = true;
        }

        if (state.ImproperPressure)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-pressure");
            foundIssue = true;
        }

        if (state.ImproperLight)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-light");
            foundIssue = true;
        }

        if (state.MissingGas > 0)
        {
            AddHealthIssue("plant-analyzer-health-issue-missing-gas");
            foundIssue = true;
        }

        if (state.WeedLevel > state.WeedTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-weeds");
            foundIssue = true;
        }

        if (state.PestLevel > state.PestTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-pests");
            foundIssue = true;
        }

        if (state.Toxins > state.ToxinsTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-toxins");
            foundIssue = true;
        }

        if (!foundIssue)
            AddHealthIssue("plant-analyzer-health-issue-none", prefix: "✓ ");
    }

    private void AddHealthIssue(string locId, string prefix = "• ")
    {
        HealthIssuesContainer.AddChild(new Label
        {
            Text = $"{prefix}{Loc.GetString(locId)}",
            StyleClasses = { "LabelSubText" },
        });
    }
    private void PopulateWarnings(PlantAnalyzerUiState state)
    {
        WarningsContainer.RemoveAllChildren();

        if (state.ImproperHeat)
            AddWarning(Loc.GetString("plant-analyzer-warning-improper-heat"));

        if (state.ImproperPressure)
            AddWarning(Loc.GetString("plant-analyzer-warning-improper-pressure"));

        if (state.ImproperLight)
            AddWarning(Loc.GetString("plant-analyzer-warning-improper-light"));

        if (state.MissingGas != 0)
            AddWarning(Loc.GetString("plant-analyzer-warning-missing-gas"));
    }

    private void PopulateTraits(PlantAnalyzerUiState state)
    {
        TraitsContainer.RemoveAllChildren();

        AddTrait(state.Viable
            ? Loc.GetString("plant-analyzer-trait-viable")
            : Loc.GetString("plant-analyzer-trait-nonviable"));

        if (state.Seedless)
            AddTrait(Loc.GetString("plant-analyzer-trait-seedless"));

        if (state.Ligneous)
            AddTrait(Loc.GetString("plant-analyzer-trait-ligneous"));

        if (state.TurnIntoKudzu)
            AddTrait(Loc.GetString("plant-analyzer-trait-kudzu"));

        if (state.CanScream)
            AddTrait(Loc.GetString("plant-analyzer-trait-screaming"));

        foreach (var mutation in state.Mutations)
            AddTrait(mutation);

        if (TraitsContainer.ChildCount == 0)
            AddTrait(Loc.GetString("plant-analyzer-trait-none"));
    }

    private void PopulateChemicals(PlantAnalyzerUiState state)
    {
        ChemicalsGrid.RemoveAllChildren();

        ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-label-chemical") });
        ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-label-chemical-current") });
        ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-label-chemical-min") });
        ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-label-chemical-max") });
        ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-label-chemical-potency-divisor") });

        if (state.Chemicals.Count == 0)
        {
            ChemicalsGrid.AddChild(new Label { Text = Loc.GetString("plant-analyzer-chemical-none") });
            return;
        }

        foreach (var chem in state.Chemicals)
        {
            ChemicalsGrid.AddChild(new Label { Text = chem.Reagent });
            ChemicalsGrid.AddChild(new Label { Text = $"{chem.CurrentAmount:F2}" });
            ChemicalsGrid.AddChild(new Label { Text = $"{chem.Min:F2}" });
            ChemicalsGrid.AddChild(new Label { Text = $"{chem.Max:F2}" });
            ChemicalsGrid.AddChild(new Label { Text = $"{chem.PotencyDivisor:F2}" });
        }
    }

    private void AddWarning(string text)
    {
        WarningsContainer.AddChild(new Label
        {
            Text = $"⚠ {text}",
        });
    }

    private void AddTrait(string text)
    {
        TraitsContainer.AddChild(new Label
        {
            Text = $"• {text}",
        });
    }

    private static string YesNo(bool value)
    {
        return Loc.GetString(value
            ? "plant-analyzer-value-yes"
            : "plant-analyzer-value-no");
    }

    private static float? GetNextHarvestAge(PlantAnalyzerUiState state)
    {
        if (state.Dead)
            return null;

        if (state.Harvest)
            return state.Age;

        // First harvest and repeat harvests both use:
        // Age - LastProduce > Production
        //
        // Since Age is an int and the condition is strictly greater-than,
        // +1 makes the displayed marker match the first whole age value
        // where the harvest check can pass.
        int startCountFrom = Math.Max(state.LastProduce, (int)MathF.Ceiling(state.Maturation));
        return startCountFrom + MathF.Floor(state.Production) + 1f;
    }
}
