using Content.Shared.Botany.PlantAnalyzer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using Robust.Client.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Net.Quic;
using SixLabors.ImageSharp.Formats.Tga;

namespace Content.Client.Botany.PlantAnalyzer;

[GenerateTypedNameReferences]
public sealed partial class PlantAnalyzerControl : BoxContainer
{
    private readonly SpriteSystem _spriteSystem;
    private static readonly Color BarGreen = new(0.20f, 0.80f, 0.25f);
    private static readonly Color BarYellow = new(1.00f, 0.78f, 0.18f);
    private static readonly Color BarRed = new(0.90f, 0.12f, 0.12f);
    private static readonly Color BarMarkerCurrent = new(0.40f, 0.80f, 1.00f, 0.85f);
    private static readonly Color BarWarningMarker = new(1.00f, 0.05f, 0.10f, 0.95f);
    private static readonly Color BarAcceptableMarker = new(0.20f, 0.80f, 0.25f, 0.95f);
    public PlantAnalyzerControl()
    {
        RobustXamlLoader.Load(this);
        _spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
    }

    public void Populate(PlantAnalyzerUiState state)
    {
        NoPlantDataText.Visible = !state.HasPlant;
        PlantDataContainer.Visible = state.HasPlant;

        if (!state.HasPlant)
        {
            NoPlantDataText.Text = Loc.GetString("plant-analyzer-interface-no-plant");
            return;
        }

        ScanModeLabel.Text = state.ScanMode
            ? Loc.GetString("plant-analyzer-interface-status-active")
            : Loc.GetString("plant-analyzer-interface-status-inactive");

        var plantName = new FormattedMessage();
        plantName.AddText(string.IsNullOrWhiteSpace(state.PlantName)
            ? Loc.GetString("plant-analyzer-value-unknown")
            : state.PlantName);

        PlantNameLabel.SetMessage(plantName);

        PopulateOverviewBars(state);
        PopulateConditionBars(state);
        PopulatePlantSprite(state);
        PopulateThreatBars(state);
        PopulatePlantChemicals(state);
        PopulateTrayChemicals(state);
        PopulateMiscMutations(state);
    }

    private void PopulatePlantSprite(PlantAnalyzerUiState state)
    {
        PlantSprite.Texture = null;
        GrowthStageLabel.Text = string.Empty;

        if (string.IsNullOrWhiteSpace(state.PlantSpriteRsi) ||
            string.IsNullOrWhiteSpace(state.PlantSpriteState))
        {
            PlantSprite.Visible = false;
            return;
        }

        PlantSprite.Visible = true;

        var sprite = new SpriteSpecifier.Rsi(
            new ResPath(state.PlantSpriteRsi),
            state.PlantSpriteState);

        PlantSprite.Texture = _spriteSystem.Frame0(sprite);

        if (state.GrowthStage > 0)
            GrowthStageLabel.Text = $"Growth stage: {state.GrowthStage}";
    }
    private void PopulateOverviewBars(PlantAnalyzerUiState state)
    {
        PopulateAgeBar(state);
        PopulateHealthBar(state);
    }

    private void PopulateAgeBar(PlantAnalyzerUiState state)
    {
        var age = MathF.Max(0f, state.Age);
        var maturation = MathF.Max(1f, state.Maturation);
        var lifespan = MathF.Max(maturation, state.Lifespan);

        Color color;
        string status;
        string tooltip;
        float capacity = MathF.Max(lifespan, age + 10f);

        if (age > lifespan)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-age-old");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-old",
                ("lifespan", $"{lifespan:0.#}"));
        }
        else if (age >= maturation)
        {
            color = BarGreen;
            status = Loc.GetString("plant-analyzer-age-mature");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-mature",
                ("lifespan", $"{lifespan:0.#}"));
        }
        else
        {
            color = BarYellow;
            status = Loc.GetString("plant-analyzer-age-growing");
            tooltip = Loc.GetString(
                "plant-analyzer-age-tooltip-growing",
                ("maturation", $"{maturation:0.#}"));
        }

        if (state.Dead)
        {
            color = BarRed;
            capacity = lifespan;
        }

        AgeStatusLabel.Text = status;

        float nextHarvestAge = GetNextHarvestAge(state) ?? capacity;
        var markerTooltip = Loc.GetString(
                state.Harvest
                    ? "plant-analyzer-age-tooltip-harvest-ready"
                    : "plant-analyzer-age-tooltip-next-harvest",
                ("age", $"{nextHarvestAge:0.#}"));

        AgeBar.SetData(
            capacity,
            Loc.GetString(
                "plant-analyzer-age-bar-text",
                ("age", $"{age:0.#}"),
                ("limit", $"{lifespan:0.#}")),
            tooltip,
            true,
            true);
        AgeBar.AddBar(start: 0f, end: age, barColor: color);
        AgeBar.AddNotch(width: 1f, height: 0.2f, bottomAlign: true);
        AgeBar.AddNotch(width: 5f, height: 0.4f, bottomAlign: true);
        //Don't show next harvest if it's dead
        if (!state.Dead)
        {
            AgeBar.AddNotch(
                width: MathF.Floor(state.Production) + 1f,
                height: 0.3f,
                offset: nextHarvestAge,
                bottomAlign: false,
                //If it's multiharvest, show all potential harvests.  Otherwise only show one.
                count: state.MultiHarvest ? 0 : 1,
                //Violet if self-harvesting, sky blue if regular harvest
                notchColor: state.AutoHarvest ? new Color(0.6f, 0.2f, 0.9f, 0.25f) : new Color(0.4f, 0.8f, 1f, 0.25f),
                tooltipText: markerTooltip);
        }
    }

    private void PopulateHealthBar(PlantAnalyzerUiState state)
    {
        var maxHealth = MathF.Max(1f, state.Endurance);
        var health = MathHelper.Clamp(state.Health, 0f, maxHealth);
        var unhealthyThreshold = maxHealth / 2f;

        var isUnhealthy = health <= unhealthyThreshold;

        var isStressed =
            !state.Viable ||
            state.Age > state.Lifespan ||
            state.ImproperHeat ||
            state.ImproperPressure ||
            state.ImproperLight ||
            state.MissingGas > 0 ||
            state.WeedLevel > state.WeedTolerance ||
            state.Toxins > state.ToxinsTolerance ||
            state.PestLevel > state.PestTolerance;

        Color color;
        string status;
        string tooltip;
        string healthText = Loc.GetString("plant-analyzer-health-bar-text",
                                            ("health", $"{health:0.#}"),
                                            ("maxHealth", $"{maxHealth:0.#}"));

        if (state.Dead)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-health-dead");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-dead");
            healthText = Loc.GetString("plant-analyzer-health-dead");
        }
        else if (isStressed)
        {
            color = isUnhealthy ? BarRed : BarYellow;
            status = Loc.GetString("plant-analyzer-health-stressed");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-stressed");
        }
        else if (isUnhealthy)
        {
            color = BarRed;
            status = Loc.GetString("plant-analyzer-health-stressed");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-unhealthy");
        }
        else
        {
            color = BarGreen;
            status = Loc.GetString("plant-analyzer-health-healthy");
            tooltip = Loc.GetString("plant-analyzer-health-tooltip-healthy");
        }

        HealthStatusLabel.Text = status;


        HealthBar.SetData(
            maxHealth,
            healthText,
            tooltip,
            true,
            true);
        if (!state.Dead)
        {
            HealthBar.AddBar(start: 0f, end: health, barColor: color);
            HealthBar.AddNotch(width: 5f, height: 0.2f, bottomAlign: true);
            HealthBar.AddNotch(width: 10f, height: 0.4f, bottomAlign: true);
        }

        PopulateHealthIssues(state, health, unhealthyThreshold);
    }

    private const float WaterWarningLevel = 10f;
    private const float NutritionWarningLevel = 5f;
    private void PopulateHealthIssues(
    PlantAnalyzerUiState state,
    float health,
    float unhealthyThreshold)
    {
        HealthIssuesContainer.RemoveAllChildren();

        var foundIssue = false;

        if (state.Dead)
        {
            AddHealthIssue("plant-analyzer-health-issue-dead");
            foundIssue = true;
            return;
        }

        if (state.Age > state.Lifespan)
        {
            AddHealthIssue("plant-analyzer-health-issue-old");
            foundIssue = true;
        }

        if (!state.Viable)
        {
            AddHealthIssue("plant-analyzer-health-issue-nonviable");
            foundIssue = true;
        }

        if (state.NutritionLevel <= NutritionWarningLevel)
        {
            AddHealthIssue("plant-analyzer-health-issue-nutrients");
            foundIssue = true;
        }

        if (state.WaterLevel <= WaterWarningLevel)
        {
            AddHealthIssue("plant-analyzer-health-issue-water");
            foundIssue = true;
        }

        if (state.ImproperHeat)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-heat");
            foundIssue = true;
        }

        if (state.ImproperPressure)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-pressure");
            foundIssue = true;
        }

        if (state.ImproperLight)
        {
            AddHealthIssue("plant-analyzer-health-issue-improper-light");
            foundIssue = true;
        }

        if (state.MissingGas > 0)
        {
            AddHealthIssue("plant-analyzer-health-issue-missing-gas");
            foundIssue = true;
        }

        if (state.WeedLevel > state.WeedTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-weeds");
            foundIssue = true;
        }

        if (state.PestLevel > state.PestTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-pests");
            foundIssue = true;
        }

        if (state.Toxins > state.ToxinsTolerance)
        {
            AddHealthIssue("plant-analyzer-health-issue-toxins");
            foundIssue = true;
        }

        if (!foundIssue)
            AddHealthIssue("plant-analyzer-health-issue-none", prefix: "✓ ");
    }

    private void AddHealthIssue(string locId, string prefix = "• ")
    {
        HealthIssuesContainer.AddChild(new Label
        {
            Text = $"{prefix}{Loc.GetString(locId)}",
            StyleClasses = { "LabelSubText" },
        });
    }

    private const float TrayResourceCapacity = 100f;
    private void PopulateConditionBars(PlantAnalyzerUiState state)
    {
        PopulateWaterBar(state);
        PopulateNutritionBar(state);
        PopulateTemperatureBar(state);
        PopulatePressureBar(state);
    }
    private static readonly Color BarColorWater = Color.FromHex("#009EDB");

    private void PopulateWaterBar(PlantAnalyzerUiState state)
    {
        var water = MathHelper.Clamp(state.WaterLevel, 0f, TrayResourceCapacity);

        WaterLevelBar.SetData(
            TrayResourceCapacity,
            $"{water:0.#}",
            Loc.GetString(
                "plant-analyzer-water-tooltip",
                ("water", $"{water:0.#}"),
                ("max", $"{TrayResourceCapacity:0.#}"),
                ("warning", $"{WaterWarningLevel:0.#}")),
            horizontal: false);

        WaterLevelBar.AddBar(
            start: 0f,
            end: water,
            barColor: BarColorWater);

        WaterLevelBar.AddNotch(
            width: 5f,
            height: 0.1f,
            offset: 0f,
            count: 0);

        WaterLevelBar.AddNotch(
            width: 10f,
            height: 0.15f,
            offset: 0f,
            count: 0);

        WaterLevelBar.AddNotch(
            width: 5f,
            height: 0.1f,
            offset: 0f,
            count: 0,
            bottomAlign: true);

        WaterLevelBar.AddNotch(
            width: 10f,
            height: 0.15f,
            offset: 0f,
            count: 0,
            bottomAlign: true);


        WaterLevelBar.AddNotch(
            width: TrayResourceCapacity,
            height: 1f,
            offset: WaterWarningLevel,
            count: 1,
            notchColor: water > WaterWarningLevel ? BarAcceptableMarker : BarWarningMarker,
            tooltipText: Loc.GetString(
                "plant-analyzer-water-warning-marker",
                ("warning", $"{WaterWarningLevel:0.#}")));
    }

    private static readonly Color BarColorNutrition = Color.FromHex("#9E6138");

    private void PopulateNutritionBar(PlantAnalyzerUiState state)
    {
        var nutrition = MathHelper.Clamp(state.NutritionLevel, 0f, TrayResourceCapacity);

        NutritionLevelBar.SetData(
            TrayResourceCapacity,
            $"{nutrition:0.#}",
            Loc.GetString(
                "plant-analyzer-nutrition-tooltip",
                ("nutrition", $"{nutrition:0.#}"),
                ("max", $"{TrayResourceCapacity:0.#}"),
                ("warning", $"{NutritionWarningLevel:0.#}")),
            horizontal: false);

        NutritionLevelBar.AddBar(
            start: 0f,
            end: nutrition,
            barColor: BarColorNutrition);

        NutritionLevelBar.AddNotch(
            width: 5f,
            height: 0.1f,
            offset: 0f,
            count: 0);

        NutritionLevelBar.AddNotch(
            width: 10f,
            height: 0.15f,
            offset: 0f,
            count: 0);

        NutritionLevelBar.AddNotch(
            width: 5f,
            height: 0.1f,
            offset: 0f,
            count: 0,
            bottomAlign: true);

        NutritionLevelBar.AddNotch(
            width: 10f,
            height: 0.15f,
            offset: 0f,
            count: 0,
            bottomAlign: true);

        NutritionLevelBar.AddNotch(
            width: TrayResourceCapacity,
            height: 1f,
            offset: NutritionWarningLevel,
            count: 1,
            notchColor: nutrition > NutritionWarningLevel ? BarAcceptableMarker : BarWarningMarker,
            tooltipText: Loc.GetString(
                "plant-analyzer-nutrition-warning-marker",
                ("warning", $"{NutritionWarningLevel:0.#}")));
    }

    private void PopulateTemperatureBar(PlantAnalyzerUiState state)
    {
        //If we're under the temp of a spaced room, we're impossibly cold and need to just ignore the values because it hasn't read the temperature yet.
        //This happens with plants of age 1.
        if (state.Age <= 1)
        {
            TemperatureBar.SetData(
                1f,
                Loc.GetString(
                    "plant-analyzer-error"),
                Loc.GetString(
                    "plant-analyzer-error-plant-too-young"
                )
            );
            return;
        }

        var current = state.Temperature;

        var ideal = state.IdealHeat;
        var tolerance = state.HeatTolerance;

        var safeMin = ideal - tolerance;
        var safeMax = ideal + tolerance;

        //padding so that we're never right on the edge of the bar
        var padding = MathF.Max(10f, tolerance * 0.5f);

        var displayMin = MathF.Min(safeMin - padding, current - padding);
        var displayMax = MathF.Max(safeMax + padding, current + padding);
        var capacity = MathF.Max(1f, displayMax - displayMin);

        float ToBarValue(float value)
        {
            return MathHelper.Clamp(value, displayMin, displayMax) - displayMin;
        }

        TemperatureBar.SetData(
            capacity: capacity,
            label: Loc.GetString(
                "plant-analyzer-temperature-bar-text",
                ("temperature", $"{current:0.#}")),
            tooltip: Loc.GetString(
                "plant-analyzer-temperature-tooltip",
                ("temperature", $"{current:0.#}"),
                ("ideal", $"{ideal:0.#}"),
                ("tolerance", $"{tolerance:0.#}")),
            horizontal: true);

        TemperatureBar.AddBar(
            start: 0f,
            end: ToBarValue(safeMin),
            barColor: BarRed);

        TemperatureBar.AddBar(
            start: ToBarValue(safeMin),
            end: ToBarValue(safeMax),
            barColor: BarGreen);

        TemperatureBar.AddBar(
            start: ToBarValue(safeMax),
            end: capacity,
            barColor: BarRed);

        TemperatureBar.AddNotch(
            width: 5f,
            height: 0.2f,
            bottomAlign: true);

        TemperatureBar.AddNotch(
            width: 10f,
            height: 0.4f,
            bottomAlign: true);

        TemperatureBar.AddNotch(
            width: capacity,
            height: 1f,
            offset: ToBarValue(current),
            count: 1,
            notchColor: BarMarkerCurrent
    );
    }

    private void PopulatePressureBar(PlantAnalyzerUiState state)
    {

        if (state.Age <= 1)
        {
            PressureBar.SetData(
                1f,
                Loc.GetString(
                    "plant-analyzer-error"),
                Loc.GetString(
                    "plant-analyzer-error-plant-too-young"
                )
            );
            return;
        }

        var current = state.Pressure;

        var safeMin = MathF.Max(0f, state.LowPressureTolerance);
        var safeMax = MathF.Max(safeMin + 1f, state.HighPressureTolerance);

        //padding so that we're never right on the edge of the bar
        var safeWidth = safeMax - safeMin;
        var padding = MathF.Max(10f, safeWidth * 0.25f);

        var displayMin = MathF.Max(0f, MathF.Min(safeMin - padding, current - padding));
        var displayMax = MathF.Max(safeMax + padding, current + padding);
        var capacity = MathF.Max(1f, displayMax - displayMin);

        float ToBarValue(float value)
        {
            return MathHelper.Clamp(value, displayMin, displayMax) - displayMin;
        }

        PressureBar.SetData(
            capacity,
            Loc.GetString(
                "plant-analyzer-pressure-bar-text",
                ("pressure", $"{current:0.#}")),
            Loc.GetString(
                "plant-analyzer-pressure-tooltip",
                ("pressure", $"{current:0.#}"),
                ("min", $"{safeMin:0.#}"),
                ("max", $"{safeMax:0.#}")),
            horizontal: true);

        // Low-pressure danger.
        PressureBar.AddBar(
            start: 0f,
            end: ToBarValue(safeMin),
            barColor: BarRed);

        // Safe pressure range.
        PressureBar.AddBar(
            start: ToBarValue(safeMin),
            end: ToBarValue(safeMax),
            barColor: BarGreen);

        // High-pressure danger.
        PressureBar.AddBar(
            start: ToBarValue(safeMax),
            end: capacity,
            barColor: BarRed);

        PressureBar.AddNotch(
            width: 5f,
            height: 0.2f,
            bottomAlign: true);

        PressureBar.AddNotch(
            width: 10f,
            height: 0.4f,
            bottomAlign: true);

        // Current pressure marker.
        PressureBar.AddNotch(
            width: capacity,
            height: 1f,
            offset: ToBarValue(current),
            count: 1,
            notchColor: BarMarkerCurrent
    );
    }

    private static readonly Color WeedColor = Color.FromHex("#B6F20D");
    private static readonly Color PestColor = Color.FromHex("#FF7F27");
    private static readonly Color ToxinColor = Color.FromHex("#A349A4");

    private void PopulateThreatBars(PlantAnalyzerUiState state)
    {
        PopulateThreatBar(
            WeedsBar,
            state.WeedLevel,
            10f,
            state.WeedTolerance,
            // Weed damage uses >= tolerance.
            state.WeedLevel >= state.WeedTolerance,
            WeedColor,
            Loc.GetString("plant-analyzer-threat-kind-weeds"));

        PopulateThreatBar(
            PestsBar,
            state.PestLevel,
            10f,
            state.PestTolerance,
            // Pest damage uses > tolerance.
            state.PestLevel > state.PestTolerance,
            PestColor,
            Loc.GetString("plant-analyzer-threat-kind-pests"));

        PopulateThreatBar(
            ToxinsBar,
            state.Toxins,
            100f,
            state.ToxinsTolerance,
            // Toxin damage uses > tolerance.
            state.Toxins > state.ToxinsTolerance,
            ToxinColor,
            Loc.GetString("plant-analyzer-threat-kind-toxins"));
    }

    private void PopulateThreatBar(
        PlantAnalyzerBar bar,
        float value,
        float maxValue,
        float damageThreshold,
        bool isDamaging,
        Color color,
        string kind)
    {
        value = MathHelper.Clamp(value, 0f, maxValue);
        damageThreshold = MathHelper.Clamp(damageThreshold, 0f, maxValue);

        string tooltip;

        if (isDamaging)
        {
            tooltip = Loc.GetString("plant-analyzer-threat-tooltip-damaging", ("kind", kind));
        }
        else if (value > 0)
        {
            tooltip = Loc.GetString("plant-analyzer-threat-tooltip-present", ("kind", kind));
        }
        else
        {
            tooltip = Loc.GetString("plant-analyzer-threat-tooltip-none", ("kind", kind));
        }

        bar.SetData(
            capacity: maxValue,
            label: $"{value:0.#}",
            tooltip: tooltip,
            horizontal: false
            );

        bar.AddBar(
            start: 0f,
            end: value,
            barColor: color);


        bar.AddNotch(
            width: maxValue / 5,
            height: 0.15f,
            offset: 0f,
            count: 0);

        bar.AddNotch(
            width: maxValue / 20,
            height: 0.1f,
            offset: 0f,
            count: 0);

        bar.AddNotch(
            width: maxValue / 5,
            height: 0.15f,
            offset: 0f,
            count: 0,
            bottomAlign: true);

        bar.AddNotch(
            width: maxValue / 20,
            height: 0.1f,
            offset: 0f,
            count: 0,
            bottomAlign: true);

        bar.Notches.Add(new PlantAnalyzerBarNotch(
            width: maxValue,
            height: 1f,
            offset: damageThreshold,
            count: 1,
            notchColor: isDamaging ? BarWarningMarker : BarAcceptableMarker,
            tooltipText: Loc.GetString(
                "plant-analyzer-threat-tolerance-marker",
                ("value", $"{damageThreshold:0.#}"))));
    }


    private void PopulatePlantChemicals(PlantAnalyzerUiState state)
    {
        PlantChemicalsContainer.RemoveAllChildren();

        if (state.Chemicals.Count == 0)
        {
            AddSubText(PlantChemicalsContainer, Loc.GetString("plant-analyzer-chem-none"));
            return;
        }

        foreach (var chem in state.Chemicals)
        {
            AddSubText(
                PlantChemicalsContainer,
                Loc.GetString(
                    "plant-analyzer-chem",
                    ("reagent", chem.Reagent),
                    ("amount", $"{chem.CurrentAmount:0.##}")));
        }
    }

    private void PopulateTrayChemicals(PlantAnalyzerUiState state)
    {
        TrayChemicalsContainer.RemoveAllChildren();

        if (state.TrayChemicals.Count == 0)
        {
            AddSubText(TrayChemicalsContainer, Loc.GetString("plant-analyzer-chem-none"));
            return;
        }

        foreach (var chem in state.TrayChemicals)
        {
            AddSubText(
                TrayChemicalsContainer,
                Loc.GetString(
                    "plant-analyzer-chem",
                    ("reagent", chem.Reagent),
                    ("amount", $"{chem.Quantity:0.##}")));
        }
    }

    private void PopulateMiscMutations(PlantAnalyzerUiState state)
    {
        MiscMutationsContainer.RemoveAllChildren();

        var found = false;

        if (!state.Viable)
        {
            AddMutation(Loc.GetString("plant-analyzer-trait-nonviable"));
            found = true;
        }

        if (state.Seedless)
        {
            AddMutation(Loc.GetString("plant-analyzer-trait-seedless"));
            found = true;
        }

        if (state.Ligneous)
        {
            AddMutation(Loc.GetString("plant-analyzer-trait-ligneous"));
            found = true;
        }

        if (state.TurnIntoKudzu)
        {
            AddMutation(Loc.GetString("plant-analyzer-trait-kudzu"));
            found = true;
        }

        if (state.CanScream)
        {
            AddMutation(Loc.GetString("plant-analyzer-trait-screaming"));
            found = true;
        }

        foreach (var mutation in state.Mutations)
        {
            AddMutation(mutation);
            found = true;
        }

        if (!found)
            AddSubText(MiscMutationsContainer, Loc.GetString("plant-analyzer-mutation-none"));
    }

    private void AddMutation(string mutation)
    {
        AddSubText(
            MiscMutationsContainer,
            Loc.GetString("plant-analyzer-mutation-entry", ("mutation", mutation)));
    }

    private static void AddSubText(BoxContainer container, string text)
    {
        container.AddChild(new Label
        {
            Text = text,
            StyleClasses = { "LabelSubText" },
        });
    }

    private static string YesNo(bool value)
    {
        return Loc.GetString(value
            ? "plant-analyzer-value-yes"
            : "plant-analyzer-value-no");
    }

    private static float? GetNextHarvestAge(PlantAnalyzerUiState state)
    {
        if (state.Dead)
            return null;

        if (state.Harvest)
            return state.Age;

        // First harvest and repeat harvests both use:
        // Age - LastProduce > Production
        //
        // Since Age is an int and the condition is strictly greater-than,
        // +1 makes the displayed marker match the first whole age value
        // where the harvest check can pass.
        int startCountFrom = Math.Max(state.LastProduce, (int)MathF.Ceiling(state.Maturation));
        return startCountFrom + MathF.Floor(state.Production) + 1f;
    }
}
